global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
    - targets:
      - localhost:9090
  - job_name: 'node_exporter'
    static_configs:
    - targets:
      - node-exporter:9100
  - job_name: 'docker-exporter'
    static_configs:
    - targets:
      - 172.17.0.1:9323
  - job_name: node_exporter_lab2
    static_configs:
    - targets:
      - 172.16.1.111:9100
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://172.16.1.111:8080
        - http://172.17.0.1:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.
