global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - localhost:9090
  - job_name: node_exporter
    static_configs:
    - targets:
      - node-exporter:9100
  - job_name: docker-exporter
    static_configs:
    - targets:
      - 172.17.0.1:9323
